[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd apps/backend && npm install"]

[phases.build]
cmds = ["cd apps/backend && npm run build"]

[start]
cmd = "cd apps/backend && npm run start"
